import AxeBuilder from '@axe-core/playwright'
import { expect, test } from '@playwright/test'

for (const mode of ['light', 'dark']) {
  test(`searchable picker filters and selects in ${mode} mode`, async ({ page }) => {
    await page.goto('/')
    if (mode === 'dark') await page.getByRole('button', { name: '切换深色模式' }).click()
    const input = page.getByRole('combobox', { name: '模型提供方' })
    await input.click()
    await input.fill('ANTHRO')
    await expect(page.getByRole('listbox').getByRole('option')).toHaveCount(1)
    await page.keyboard.press('Enter')
    await expect(input).toHaveValue('Anthropic')
    await input.click()
    await input.fill('missing provider')
    await expect(page.locator('.cake-combobox-search').getByRole('status')).toHaveText('没有匹配的提供方')
    await page.keyboard.press('Escape')
    await expect(input).toHaveValue('Anthropic')
    await expect(input).toBeFocused()
    await input.click()
    const result = await new AxeBuilder({ page })
      .include('.cake-combobox-search')
      .withTags(['wcag2a', 'wcag2aa', 'wcag21aa'])
      .analyze()
    expect(result.violations).toEqual([])
    await page.getByRole('option', { name: 'OpenAI 云服务' }).click()
    await expect(input).toHaveValue('OpenAI')
    await input.click()
    await page.getByRole('heading', { name: '输入与选择', exact: true }).click()
    await expect(input).toHaveAttribute('aria-expanded', 'false')
  })
}

test('dialog picker validates, scrolls a long list, and cancels before the enclosing dialog', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('/tests/browser/fixtures/combobox/index.html')
  await page.getByRole('button', { name: 'Choose provider' }).click()
  const input = page.getByRole('combobox', { name: 'Provider', exact: true })
  const dialog = page.getByRole('dialog', { name: 'Provider settings' })
  await expect(input).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(dialog).toBeVisible()
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(input).toBeFocused()
  await expect(page.getByLabel('Saved provider')).toBeEmpty()
  await input.fill('Provider 99')
  await page.keyboard.press('Enter')
  await expect(input).toHaveValue('Provider 99')
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.getByLabel('Saved provider')).toHaveText('provider-99')
  await page.getByRole('button', { name: 'Reset' }).click()
  await expect(input).toHaveValue('Choose a provider')
  await input.click()
  await page.keyboard.press('ArrowDown')
  await page.keyboard.press('Enter')
  await expect(input).toHaveValue('Provider 0')
  await input.click()
  const popup = page.locator('.cake-combobox-search-popup')
  await popup.hover()
  await page.mouse.wheel(0, 10000)
  const last = page.getByRole('option', { name: 'Provider 99 Available', exact: true })
  await expect(last).toBeInViewport()
  await last.click()
  await expect(input).toHaveValue('Provider 99')
  await input.click()
  await page.keyboard.press('Escape')
  await expect(dialog).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(dialog).not.toBeVisible()
  expect(errors).toEqual([])
})

test('touch picker stays in the viewport and allows scrolling and selection', async ({ browser }) => {
  const context = await browser.newContext({ viewport: { width: 390, height: 844 }, hasTouch: true, isMobile: true })
  const page = await context.newPage()
  await page.goto(`${test.info().project.use.baseURL}/tests/browser/fixtures/combobox/index.html`)
  await page.getByRole('button', { name: 'Choose provider' }).tap()
  const input = page.getByRole('combobox', { name: 'Provider', exact: true })
  const popup = page.locator('.cake-combobox-search-popup')
  const bounds = await popup.boundingBox()
  expect(bounds!.x).toBeGreaterThanOrEqual(0)
  expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(390)
  expect(bounds!.y).toBeGreaterThanOrEqual(0)
  expect(bounds!.y + bounds!.height).toBeLessThanOrEqual(844)
  const cdp = await context.newCDPSession(page)
  const x = bounds!.x + bounds!.width / 2
  const y = bounds!.y + bounds!.height - 30
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x, y }] })
  for (let offset = 20; offset < 160; offset += 20) {
    await cdp.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x, y: y - offset }] })
  }
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
  await expect.poll(() => page.getByRole('listbox').evaluate((element) => element.scrollTop)).toBeGreaterThan(0)
  await expect(input).toHaveAttribute('aria-expanded', 'true')
  await input.fill('Provider 99')
  await page.getByRole('option', { name: 'Provider 99 Available', exact: true }).tap()
  await expect(input).toHaveValue('Provider 99')
  await context.close()
})
