import AxeBuilder from '@axe-core/playwright'
import { expect, test } from '@playwright/test'

test('themes, search, code samples and task composition work', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('/')
  await expect(page.getByRole('button', { name: '蓝', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: '蓝', exact: true }).click()
  await expect(page.locator('.demo-app')).toHaveAttribute('data-theme', 'blue')
  await page.reload()
  await expect(page.locator('.demo-app')).toHaveAttribute('data-theme', 'blue')
  await page.getByRole('button', { name: '切换深色模式' }).click()
  await expect(page.locator('.demo-app')).toHaveAttribute('data-mode', 'dark')
  await page.getByRole('textbox', { name: '搜索组件' }).fill('Button')
  await expect(page.locator('.demo-section')).toHaveCount(2)
  await page.getByRole('button', { name: '查看按钮与提示代码' }).click()
  await expect(page.locator('#actions .demo-code')).toContainText('<Button')
  await page.getByRole('textbox', { name: '搜索组件' }).fill('does-not-exist')
  await expect(page.getByText('没有找到「does-not-exist」相关组件。')).toBeVisible()
  await page.getByRole('button', { name: '应用示例', exact: true }).click()
  await page.getByRole('button', { name: '新建任务', exact: true }).click()
  await page.getByRole('textbox', { name: '任务名称' }).fill('测试真实任务流程')
  const category = page.getByRole('combobox', { name: '分类', exact: true })
  await category.click()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog', { name: '新建任务', exact: true })).toBeVisible()
  await expect(category).toBeFocused()
  await category.click()
  await page.getByRole('option', { name: '文档', exact: true }).click()
  await expect(category).toHaveValue('文档')
  await page.getByRole('button', { name: '创建任务', exact: true }).click()
  await page.getByRole('checkbox', { name: '测试真实任务流程' }).check()
  await page.getByRole('tab', { name: '已完成', exact: true }).click()
  await expect(page.getByRole('checkbox', { name: '测试真实任务流程' })).toBeChecked()
  expect(errors).toEqual([])
})

test('dialog traps focus, dismisses on Escape, restores focus and retains theme', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '金', exact: true }).click()
  const trigger = page.getByRole('button', { name: '打开对话框' })
  await trigger.click()
  const dialog = page.getByRole('dialog', { name: '重命名资源' })
  await expect(dialog).toBeVisible()
  await expect(page.getByRole('textbox', { name: '资源名称' })).toBeFocused()
  for (let index = 0; index < 8; index++) {
    await page.keyboard.press('Tab')
    expect(await dialog.evaluate((element) => element.contains(document.activeElement))).toBe(true)
  }
  expect(await dialog.evaluate((element) => getComputedStyle(element).getPropertyValue('--cake-accent').trim())).toBe(
    '#8b654a'
  )
  await page.keyboard.press('Escape')
  await expect(dialog).not.toBeVisible()
  await expect(trigger).toBeFocused()
  await trigger.click()
  await page.getByRole('textbox', { name: '资源名称' }).fill('新名称')
  await page.keyboard.press('Enter')
  await expect(dialog).not.toBeVisible()
  await expect(page.locator('.cake-toast')).toContainText('新名称')
})

test('context menu is clamped to viewport and supports keyboard selection', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('switch', { name: 'Interactive 模式' }).uncheck()
  const trigger = page.getByLabel('设计资源，右键或 Shift F10 打开菜单', { exact: true })
  await trigger.focus()
  await page.keyboard.press('Shift+F10')
  const menu = page.getByRole('menu', { name: '文件操作' })
  await expect(menu).toBeVisible()
  await expect(page.getByRole('menuitem', { name: '重命名' })).toBeFocused()
  await page.keyboard.press('ArrowDown')
  await expect(page.getByRole('menuitem', { name: '创建副本' })).toBeFocused()
  await page.keyboard.press('ArrowDown')
  await expect(page.getByRole('menuitem', { name: '移至回收站' })).toBeFocused()
  await page.keyboard.press('Home')
  await page.keyboard.press('Enter')
  await expect(menu).not.toBeVisible()
  await expect(page.getByRole('dialog', { name: '重命名资源' })).toBeVisible()
  await page.keyboard.press('Escape')
  await trigger.click({ button: 'right' })
  const bounds = await menu.boundingBox()
  expect(bounds).not.toBeNull()
  expect(bounds!.x).toBeGreaterThanOrEqual(0)
  expect(bounds!.y + bounds!.height).toBeLessThanOrEqual(1050)
  await page.keyboard.press('Escape')
  await expect(trigger).toBeFocused()
})

test('old automatic palette becomes blue and new explicit choices persist', async ({ page }) => {
  await page.goto('/')
  await page.evaluate(() =>
    localStorage.setItem('cakeui-demo-settings', JSON.stringify({ theme: 'pink', mode: 'dark' }))
  )
  await page.reload()
  await expect(page.locator('.demo-app')).toHaveAttribute('data-theme', 'blue')
  await expect(page.locator('.demo-app')).toHaveAttribute('data-mode', 'dark')
  await page.getByRole('button', { name: '金', exact: true }).click()
  await page.reload()
  await expect(page.locator('.demo-app')).toHaveAttribute('data-theme', 'gold')
})

test('interactive menu opens on right down, depresses its trigger, and selects only on release', async ({ page }) => {
  await page.goto('/')
  const trigger = page.getByLabel('设计资源，右键或 Shift F10 打开菜单', { exact: true })
  const menu = page.getByRole('menu', { name: '文件操作' })
  await trigger.hover()
  await page.mouse.down({ button: 'right' })
  await expect(menu).toBeVisible()
  await expect(menu).toBeFocused()
  await expect(trigger).toHaveCSS('transform', 'matrix(1, 0, 0, 1, 0, 1)')
  await expect(menu).toHaveCSS('transform', 'none')
  const pressedBounds = await menu.boundingBox()
  const positioned = await menu.evaluate((element) => ({
    x: parseFloat(element.style.left),
    y: parseFloat(element.style.top),
  }))
  expect(pressedBounds!.x).toBeCloseTo(positioned.x, 0)
  expect(pressedBounds!.y).toBeCloseTo(positioned.y, 0)
  const copy = page.getByRole('menuitem', { name: '创建副本', exact: true })
  await copy.evaluate((element) =>
    element.addEventListener('click', () => {
      element.dataset.clickCount = String(Number(element.dataset.clickCount ?? '0') + 1)
    })
  )
  await copy.locator('.cake-menuitem-label').hover()
  await expect(page.locator('.cake-toast')).not.toBeVisible()
  await page.screenshot({ path: 'test-results/contextmenu-interactive-pressed.png' })
  await page.mouse.up({ button: 'right' })
  await expect(menu).not.toBeVisible()
  await expect(trigger).toHaveCSS('transform', 'none')
  await expect(page.locator('.cake-menuitem').filter({ hasText: '创建副本' })).toHaveAttribute('data-click-count', '1')
  await expect(page.locator('.cake-toast')).toContainText('已创建副本：设计资源 副本')
  // A late platform contextmenu must not reopen the just-selected menu.
  await trigger.evaluate((element) =>
    element.dispatchEvent(
      new MouseEvent('contextmenu', { button: 2, bubbles: true, cancelable: true, clientX: 100, clientY: 100 })
    )
  )
  await expect(menu).not.toBeVisible()
})

test('interactive release on blank space, separators or disabled items keeps the menu open', async ({ page }) => {
  await page.goto('/')
  const trigger = page.getByLabel('设计资源，右键或 Shift F10 打开菜单', { exact: true })
  const menu = page.getByRole('menu', { name: '文件操作' })
  for (const target of ['padding', 'outside', 'separator', 'disabled']) {
    await trigger.hover()
    await page.mouse.down({ button: 'right' })
    await expect(menu).toBeVisible()
    if (target === 'outside') await page.getByRole('heading', { name: '浮层与菜单', exact: true }).hover()
    if (target === 'separator') await menu.locator('.cake-menu-separator').hover()
    if (target === 'disabled') await page.getByRole('menuitem', { name: '复制共享链接' }).hover()
    await page.mouse.up({ button: 'right' })
    await expect(menu).toBeVisible()
    await expect(trigger).toHaveCSS('transform', 'none')
    await expect(page.locator('.cake-toast')).not.toBeVisible()
    await page.keyboard.press('Escape')
    await expect(menu).not.toBeVisible()
  }
  await trigger.click({ button: 'right' })
  await expect(menu).toBeVisible()
  await page.getByRole('menuitem', { name: '重命名' }).click()
  await expect(page.getByRole('dialog', { name: '重命名资源' })).toBeVisible()
  await page.keyboard.press('Escape')
  await trigger.hover()
  await page.mouse.down({ button: 'right' })
  await page.getByRole('menuitem', { name: '重命名' }).hover()
  await page.mouse.up({ button: 'right' })
  await expect(menu).not.toBeVisible()
  await expect(page.getByRole('dialog', { name: '重命名资源' })).toBeVisible()
  await expect(page.getByRole('textbox', { name: '资源名称' })).toBeFocused()
})

test('interactive gestures cancel safely and retain normal keyboard and outside-click behavior', async ({ page }) => {
  await page.goto('/')
  const trigger = page.getByLabel('设计资源，右键或 Shift F10 打开菜单', { exact: true })
  const menu = page.getByRole('menu', { name: '文件操作' })
  await trigger.hover()
  await page.mouse.down({ button: 'right' })
  await expect(menu).toBeVisible()
  await page.keyboard.press('Escape')
  await page.mouse.up({ button: 'right' })
  await expect(menu).not.toBeVisible()
  await expect(trigger).toHaveCSS('transform', 'none')
  await trigger.press('Shift+F10')
  await expect(page.getByRole('menuitem', { name: '重命名' })).toBeFocused()
  await page.keyboard.press('ArrowDown')
  await expect(page.getByRole('menuitem', { name: '创建副本', exact: true })).toBeFocused()
  await page.getByRole('heading', { name: '浮层与菜单', exact: true }).click()
  await expect(menu).not.toBeVisible()
  await trigger.hover()
  await page.mouse.down({ button: 'right' })
  await expect(menu).toBeVisible()
  await page.evaluate(() => window.dispatchEvent(new Event('blur')))
  await page.mouse.up({ button: 'right' })
  await expect(menu).not.toBeVisible()
  await expect(trigger).toHaveCSS('transform', 'none')
})

test('tooltips open on focus and escape, native tabs and log filters work', async ({ page }) => {
  await page.goto('/')
  const hint = page.getByRole('button', { name: '关于按钮' })
  await hint.focus()
  await expect(page.getByRole('tooltip')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('tooltip')).not.toBeVisible()
  await page.getByRole('tab', { name: '文件' }).focus()
  await page.keyboard.press('ArrowRight')
  await expect(page.getByRole('tab', { name: '最近动态' })).toHaveAttribute('aria-selected', 'true')
  await page.getByRole('combobox', { name: '日志级别' }).selectOption('warning')
  await expect(page.getByRole('log').locator('.cake-logentry')).toHaveCount(1)
  await page.getByRole('combobox', { name: '日志级别' }).selectOption('all')
  await page.getByRole('button', { name: '追加日志' }).click()
  await expect(page.getByRole('log').locator('.cake-logentry')).toHaveCount(6)
})

for (const mode of ['light', 'dark'] as const) {
  test(`combo popup supports pointer, keyboard and dismissal in ${mode} mode`, async ({ page }) => {
    await page.goto('/')
    if (mode === 'dark') await page.getByRole('button', { name: '切换深色模式' }).click()
    const select = page.getByRole('combobox', { name: '同步方式', exact: true })
    await select.click()
    await expect(select).toHaveCSS('appearance', 'base-select')
    const manual = page.getByRole('option', { name: '手动同步', exact: true })
    await expect(manual).toBeVisible()
    await manual.click()
    await expect(select).toHaveValue('manual')
    await expect(select).toBeFocused()
    await page.keyboard.press('Space')
    await page.keyboard.press('ArrowDown')
    await page.keyboard.press('Enter')
    await expect(select).toHaveValue('wifi')
    await select.click()
    await page.keyboard.press('ArrowUp')
    await page.keyboard.press('Escape')
    await expect(select).toHaveValue('wifi')
    await expect(select).toBeFocused()
    await select.click()
    await page.getByRole('heading', { name: '输入与选择', exact: true }).click()
    await expect(manual).not.toBeVisible()
    await page.setViewportSize({ width: 390, height: 844 })
    await select.click()
    await expect(manual).toBeVisible()
    const bounds = await manual.boundingBox()
    expect(bounds!.x).toBeGreaterThanOrEqual(0)
    expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(390)
    expect(bounds!.y).toBeGreaterThanOrEqual(0)
    expect(bounds!.y + bounds!.height).toBeLessThanOrEqual(844)
    await page.screenshot({ path: `test-results/combobox-${mode}.png` })
    await manual.click()
    await expect(select).toHaveValue('manual')
  })

  test(`no serious accessibility violations in ${mode} mode`, async ({ page }) => {
    await page.goto('/')
    if (mode === 'dark') await page.getByRole('button', { name: '切换深色模式' }).click()
    const result = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()
    expect(result.violations).toEqual([])
    await page.getByRole('button', { name: '设计变量', exact: true }).click()
    const tokens = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()
    expect(tokens.violations).toEqual([])
  })
}

test('mobile layout and reduced motion remain usable', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  expect(
    await page
      .locator('.demo-app')
      .evaluate((element) => getComputedStyle(element).getPropertyValue('--cake-fast').trim())
  ).toBe('0ms')
  await page.getByRole('button', { name: '展开导航' }).click()
  await expect(page.getByRole('button', { name: '组件总览', exact: true })).toBeFocused()
  await page.getByRole('button', { name: '开始使用', exact: true }).click()
  await expect(page.getByRole('heading', { name: '从一个 import 开始。' })).toBeVisible()
  await page.getByRole('button', { name: '展开导航' }).click()
  await page.getByRole('button', { name: '组件总览', exact: true }).click()
  await page.screenshot({ path: 'test-results/mobile.png', fullPage: true })
})

test('capture desktop overview', async ({ page }) => {
  await page.goto('/')
  await page.screenshot({ path: 'test-results/desktop.png', fullPage: true })
})
