export { SlideDeck, type SlideDeckProps, type SlideDeckLabels } from './components/SlideDeck'
export { Slide, type SlideProps, type SlideRatio } from './components/Slide'
export { SlideHeader, type SlideHeaderProps } from './components/SlideHeader'
export { SlideTitle, type SlideTitleProps } from './components/SlideTitle'
export { SlideText, type SlideTextProps } from './components/SlideText'
export { SlideFooter, type SlideFooterProps } from './components/SlideFooter'
export { SlideColumns, type SlideColumnsProps } from './components/SlideColumns'
export { SlidePanel, type SlidePanelProps } from './components/SlidePanel'
export { SlideList, type SlideListProps } from './components/SlideList'
export { SlideListItem, type SlideListItemProps } from './components/SlideListItem'
export { SlideStat, type SlideStatProps } from './components/SlideStat'
export { SlideFigure, type SlideFigureProps } from './components/SlideFigure'
export { SlideImage, type SlideImageProps } from './components/SlideImage'
export { SlideQuote, type SlideQuoteProps } from './components/SlideQuote'
export { SlideCode, type SlideCodeProps } from './components/SlideCode'
